name: CI
on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "latest"
          cache: "npm"
          working-directory: ./frontend

      - name: Install Dependencies
        run: npm install
        working-directory: ./frontend

      - name: Lint
        run: npm run lint
        working-directory: ./frontend

      - name: Test
        run: echo "#npm run test"
        working-directory: ./frontend
